# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    types:
      - review

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    uses: open-vela/public-actions/.github/workflows/ci.yml@trunk
    secrets: inherit
